---
title: OWA Lineage CTmax Project
date: "`r Sys.Date()`"
output: 
  html_document:
          code_folding: hide
          code_download: true
          toc: true
          toc_float: true
  github_document:
          html_preview: false
          toc: true
          toc_depth: 3
---

```{r setup, include=T, message = F, warning = F, echo = F}
knitr::opts_chunk$set(
  echo = knitr::is_html_output(),
  fig.align = "center",
  fig.path = "../Figures/markdown/",
  message = FALSE,
  warning = FALSE,
  collapse = T,
  dev = c("png", "pdf")
)

theme_matt = function(base_size){
  ggpubr::theme_pubr(base_family="sans") %+replace% 
    theme(
      panel.background  = element_blank(),
      plot.background = element_rect(fill="transparent", colour=NA), 
      legend.background = element_rect(fill="transparent", colour=NA),
      legend.key = element_rect(fill="transparent", colour=NA),
      legend.text = element_text(size=base_size * 0.9),
      legend.title = element_text(size = base_size * 0.9, 
                                  face = "bold"),
      axis.text = element_text(size = base_size),
      axis.title = element_text(size = base_size * 1.2),
      title = element_text(size = base_size * 1.55)
    )
}

lineage_cols = c("AA" = "#0C7BDF",
                 "AH" = "#009D77", 
                 "HA" = "#FFA602", 
                 "HH" = "#D55D07")
```

```{r}
knitr::kable(table(full_data$lineage))
```

```{r}
ggplot(full_data, aes(x = lineage, y = length, fill = lineage)) + 
  geom_boxplot() + 
  geom_point(size = 2, position = position_jitter(width = 0.1, height = 0)) + 
  scale_fill_manual(values = lineage_cols) + 
  labs(x = "Lineage", 
       y = "Length (mm)") + 
  theme_matt(base_size = 18) + 
  theme(legend.position = "none")
```

```{r}
ggplot(full_data, aes(x = lineage, y = ctmax, fill = lineage)) + 
  geom_boxplot() + 
  geom_point(position = position_jitter(width = 0.1, height = 0)) + 
  scale_fill_manual(values = lineage_cols) + 
  labs(x = "Lineage", 
       y = "CTmax (degrees C)") + 
  theme_matt(base_size = 18) + 
  theme(legend.position = "none")
```

```{r}
ggplot(full_data, aes(x = length, y = ctmax)) + 
  geom_smooth(method = "lm", colour = "black") + 
  geom_point(size = 2, aes(colour = lineage)) + 
  scale_colour_manual(values = lineage_cols) + 
  labs(x = "Length (mm)", 
       y = "CTmax (degrees C)") + 
  theme_matt(base_size = 18)
```



